name: Autograding Tests
'on':
- push
- workflow_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Bucket 80
      id: bucket-80
      uses: classroom-resources/autograding-python-grader@v1
      with:
        test-name: Bucket 80
        timeout: 10
        max-score: 80
        setup-command: "sh config_test.sh 80; pip install \".[classroom]\""
    - name: Bucket 100
      id: bucket-100
      uses: classroom-resources/autograding-python-grader@v1
      with:
        test-name: bucket-100
        timeout: 10
        max-score: 20
        setup-command: "sh config_test.sh 100; pip install \".[classroom]\""
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        BUCKET-80_RESULTS: "${{steps.bucket-80.outputs.result}}"
        BUCKET-100_RESULTS: "${{steps.bucket-100.outputs.result}}"
      with:
        runners: bucket-80,bucket-100
