name: Pull Request Autograding
on:
  pull_request:
    branches: ["master"]
jobs:
  autograding:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --editable ".[classroom]"
    - name: Pre-commit
      uses: pre-commit/action@v3.0.1
    - name: Passoff Bucket 80
      run: |
        pytest --no-header --no-summary -s -v -vv test/test_passoff_80.py
      if: always()
    - name: Passoff Bucket 100
      run: |
        pytest --no-header --no-summary -s -v -vv test/test_passoff_100.py
      if: always()
